#!/bin/sh
if [ ! -f "$(dirname "$0")/_/husky.sh" ]; then
  npx husky install
fi
. "$(dirname "$0")/_/husky.sh"

# ts-node src/cli/index.ts loadDeps ./ ts && npm run lint-staged && npm run build 
ts-node src/cli/index.ts loadDeps ./ ts && npm run lint-staged
